[project]
name = "gz-sim-yarp-plugins"
# As this version is currently ignored, we do not
# waste effort in mantain it in synch with the value
# specified in CMakeLists.txt
version = "0.0.0"
description = "YARP plugins for Modern Gazebo (gz-sim). "
authors = ["Alessandro Croci <alessandro.croci@iit.it", "Silvio Traversaro <silvio.traversaro@iit.it>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]

[activation.env]
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"
GZ_SIM_SYSTEM_PLUGIN_PATH = "$CONDA_PREFIX/lib"

[target.win-64.activation.env]
CMAKE_INSTALL_PREFIX = "%CONDA_PREFIX%\\Library"
GZ_SIM_SYSTEM_PLUGIN_PATH = "%CONDA_PREFIX%\\Library\\bin"

[feature.harmonic.activation.env]
GSYP_BUILD_DIRECTORY_NAME = ".build_harmonic"

[feature.ionic.activation.env]
GSYP_BUILD_DIRECTORY_NAME = ".build_ionic"

[feature.jetty.activation.env]
GSYP_BUILD_DIRECTORY_NAME = ".build_ionic"

[tasks]

configure = { cmd = [
    "cmake",
    "-DCMAKE_BUILD_TYPE=Release",
    "-DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX",
    "-DBUILD_TESTING:BOOL=ON",
    "-DGZ_SIM_YARP_PLUGINS_ENABLE_TESTS_WITH_ICUB_MAIN:BOOL=OFF",
    # Use the cross-platform Ninja generator
    "-G",
    "Ninja",
    # The source is in the root directory
    "-S",
    ".",
    # We wanna build in the $GSYP_BUILD_DIRECTORY_NAME directory
    "-B",
    "$GSYP_BUILD_DIRECTORY_NAME"
]}

build = { cmd = "cmake --build $GSYP_BUILD_DIRECTORY_NAME --config Release", depends-on = ["configure"] }
test = { cmd = "ctest --test-dir $GSYP_BUILD_DIRECTORY_NAME --build-config Release --output-on-failure", depends-on = ["build"] }
install = { cmd = ["cmake", "--install", "$GSYP_BUILD_DIRECTORY_NAME", "--config", "Release"], depends-on = ["build"] }
uninstall = { cmd = ["cmake", "--build", "$GSYP_BUILD_DIRECTORY_NAME", "--target", "uninstall"]}
cpp-fmt = "fd --extension h --extension hh --extension hpp --extension c --extension cc --extension cpp --exec clang-format -i --verbose"

[dependencies]
yarp = "*"
ycm-cmake-modules = "*"
cmake = "*"
ninja = "*"
pkg-config = "*"
cxx-compiler = "*"
gtest = "*"
fd-find = "*"
clang-format = "18.*"
icub-main = "*"

[target.linux-64.dependencies]
libgl-devel = "*"
libopengl-devel = "*"
libegl-devel = "*"

[target.linux-aarch64.dependencies]
libgl-devel = "*"
libopengl-devel = "*"
libegl-devel = "*"

[feature.harmonic.dependencies]
libgz-sim = "8.*"

[feature.ionic.dependencies]
libgz-sim = "9.*"

[feature.jetty.dependencies]
libgz-sim = "10.*"

[environments]
default = ["jetty"]
harmonic = ["harmonic"]
ionic = ["ionic"]
jetty = ["jetty"]
