name: Run tests with pixi

on:
  workflow_dispatch:
  pull_request:

jobs:
  pixi-test:
    name: '[pixi:${{ matrix.os }}:env:${{ matrix.pixi_env }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04,
          macos-latest,
          windows-2019
        ]
        pixi_env: [
          default,
          ionic
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Install mesa (software only) OpenGL driver
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update
        # See https://github.com/robotology/gz-sim-yarp-plugins/pull/214#issuecomment-2387088665
        sudo apt install libegl-mesa0 libgl1-mesa-dri

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        run-install: true
        cache: false

    - name: Print pixi info
      run: pixi info

    - name: Build the project
      run: pixi run -e ${{ matrix.pixi_env }} build

    # Windows disabled due to https://github.com/robotology/gz-sim-yarp-plugins/issues/205
    # macOS on Harmonic disabled due to https://github.com/robotology/gz-sim-yarp-plugins/pull/253#issuecomment-2732223851
    - name: Run tests
      if: "!contains(matrix.os, 'windows') && !(contains(matrix.os, 'macos') && matrix.pixi_env == 'default')"
      run: pixi run -e ${{ matrix.pixi_env }} test
