name: Run tests with pixi

on:
  workflow_dispatch:
  pull_request:

jobs:
  pixi-test:
    name: '[pixi:${{ matrix.os }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04,
          macos-latest,
          # Disabled until https://github.com/robotology/gz-sim-yarp-plugins/issues/205 is fixed
          # windows-2019
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Install mesa (software only) OpenGL driver
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update
        # See https://github.com/robotology/gz-sim-yarp-plugins/pull/214#issuecomment-2387088665
        sudo apt install libegl-mesa0 libgl1-mesa-dri

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        run-install: true
        cache: false

    - name: Print pixi info
      run: pixi info

    - name: Run tests
      run: pixi run test
